services:
  - type: web
    name: inventory-app
    runtime: node
    plan: free
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm start"
    envVars:
      - key: MONGO_URI
        scope: run
        value: ${MONGO_URI}
      - key: JWT_SECRET
        scope: run
        value: ${JWT_SECRET}
      - key: FRONTEND_URL
        scope: run
        value: https://${RENDER_EXTERNAL_HOSTNAME}
      - key: NODE_ENV
        value: production